# Generated by Django 4.2.27 on 2025-12-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва групи')),
                ('amount', models.PositiveIntegerField(verbose_name='Кількість студентів')),
                ('start_year', models.IntegerField(verbose_name='Рік початку навчання')),
            ],
            options={
                'verbose_name': 'Група',
                'verbose_name_plural': 'Групи',
            },
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
