# Generated by Django 4.2.27 on 2025-12-07 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва типу')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Короткий опис')),
            ],
            options={
                'verbose_name': 'Тип аудиторії',
                'verbose_name_plural': 'Типи аудиторій',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назва/Номер аудиторії')),
                ('building', models.CharField(max_length=50, verbose_name='Корпус')),
                ('capacity', models.PositiveIntegerField(verbose_name='Місткість')),
                ('note', models.TextField(blank=True, verbose_name='Примітка')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='api.roomtype', verbose_name='Тип аудиторії')),
            ],
            options={
                'verbose_name': 'Аудиторія',
                'verbose_name_plural': 'Аудиторії',
            },
        ),
    ]
