# Generated by Django 4.2.27 on 2025-12-07 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_roomtype_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва семестру')),
                ('start_date', models.DateField(verbose_name='Дата початку')),
                ('end_date', models.DateField(verbose_name='Дата завершення')),
                ('configuration', models.JSONField(blank=True, default=dict, verbose_name='Налаштування генерації')),
            ],
            options={
                'verbose_name': 'Семестр',
                'verbose_name_plural': 'Семестри',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Час початку')),
                ('end_time', models.TimeField(verbose_name='Час завершення')),
                ('day_name', models.CharField(blank=True, max_length=20)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='api.semester')),
            ],
            options={
                'verbose_name': 'Часовий слот',
                'verbose_name_plural': 'Часові слоти',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
