# Generated by Django 4.2.27 on 2025-12-07 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_semester_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип заняття')),
            ],
            options={
                'verbose_name': 'Тип заняття',
                'verbose_name_plural': 'Типи занять',
            },
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='Скільки разів це заняття має відбутися за семестр', verbose_name='Кількість занять')),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.classtype', verbose_name='Тип заняття')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to='api.group', verbose_name='Група')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to='api.semester', verbose_name='Семестр')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to='api.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to='api.teacher', verbose_name='Викладач')),
            ],
            options={
                'verbose_name': 'План заняття',
                'verbose_name_plural': 'Навчальний план',
                'unique_together': {('semester', 'group', 'subject', 'teacher', 'class_type')},
            },
        ),
    ]
