# Generated by Django 4.2.27 on 2025-12-07 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0007_classtype_studyplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(related_name='lessons', to='api.group', verbose_name='Групи')),
                ('lesson_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.classtype', verbose_name='Тип заняття')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='api.room', verbose_name='Аудиторія')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='api.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='api.teacher', verbose_name='Викладач')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='api.timeslot', verbose_name='Слот часу')),
            ],
            options={
                'verbose_name': 'Заняття',
                'verbose_name_plural': 'Заняття',
            },
        ),
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва обмеження')),
                ('constraint_type', models.CharField(choices=[('TIME_AVAILABILITY', 'Доступність по часу (Global/Teacher/Group)'), ('ROOM_REQUIREMENT', 'Вимоги до аудиторії (Subject/LessonType)'), ('GROUP_MERGE', "Об'єднання груп (Lectures)"), ('SEQUENCE', 'Послідовність предметів'), ('MAX_DAILY_LOAD', 'Максимальне навантаження на день'), ('NO_WINDOWS', 'Відсутність вікон')], max_length=50, verbose_name='Тип обмеження')),
                ('priority', models.IntegerField(default=10, verbose_name='Пріоритет (вага)')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('configuration', models.JSONField(blank=True, default=dict, verbose_name='Конфігурація')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Обмеження',
                'verbose_name_plural': 'Обмеження',
            },
        ),
    ]
