# Generated by Django 4.2.27 on 2025-12-08 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_lesson_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_type',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='room',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='time_slot',
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_plans', to='api.group', verbose_name='Група'),
        ),
        migrations.DeleteModel(
            name='Constraint',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
