# Generated by Django 4.2.27 on 2025-12-08 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_lesson_groups_remove_lesson_lesson_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studyplan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Код типу'),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='constraints',
            field=models.JSONField(blank=True, default=dict, verbose_name='Додаткові вимоги'),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='duration',
            field=models.PositiveIntegerField(default=1, help_text='Duration in pairs', verbose_name='Тривалість (пар)'),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='required_room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.roomtype', verbose_name='Необхідний тип аудиторії'),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='study_plans', to='api.group', verbose_name='Група'),
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва потоку')),
                ('groups', models.ManyToManyField(related_name='streams', to='api.group', verbose_name='Групи')),
            ],
            options={
                'verbose_name': 'Потік',
                'verbose_name_plural': 'Потоки',
            },
        ),
        migrations.AddField(
            model_name='studyplan',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='study_plans', to='api.stream', verbose_name='Потік'),
        ),
    ]
