# Generated by Django 4.2.27 on 2025-12-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_studyplan_unique_together_roomtype_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Код типу'),
        ),
        migrations.AddConstraint(
            model_name='studyplan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', False), ('stream__isnull', True)), models.Q(('group__isnull', True), ('stream__isnull', False)), _connector='OR'), name='study_plan_group_xor_stream'),
        ),
    ]
