# Generated by Django 4.2.27 on 2025-12-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_roomtype_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='day_of_week',
            field=models.IntegerField(default=1, verbose_name='День тижня (1-7)'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступний для планування'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='period_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер пари'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='week_type',
            field=models.CharField(choices=[('FULL', 'Постійно'), ('NUMERATOR', 'Чисельник'), ('DENOMINATOR', 'Знаменник')], default='FULL', max_length=20, verbose_name='Тип тижня'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['semester', 'week_type', 'day_of_week', 'period_number'], name='api_timeslo_semeste_f7bbd4_idx'),
        ),
    ]
