# Generated by Django 4.2.27 on 2025-12-08 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_timeslot_day_of_week_timeslot_is_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration', models.JSONField(help_text='Example: {"banned_days": [1, 5], "banned_periods": [4]}', verbose_name='Конфігурація обмеження')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester_constraints', to='api.group')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester_constraints', to='api.room')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='api.semester')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester_constraints', to='api.stream')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester_constraints', to='api.teacher')),
            ],
            options={
                'verbose_name': 'Обмеження семестру',
                'verbose_name_plural': 'Обмеження семестрів',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_locked', models.BooleanField(default=False, help_text='Manually pinned by user', verbose_name='Закріплено')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='api.room')),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='api.studyplan')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='api.timeslot')),
            ],
            options={
                'verbose_name': 'Заняття',
                'verbose_name_plural': 'Заняття',
                'indexes': [models.Index(fields=['time_slot', 'room'], name='api_lesson_time_sl_ec1017_idx'), models.Index(fields=['study_plan'], name='api_lesson_study_p_5196bd_idx')],
                'unique_together': {('room', 'time_slot')},
            },
        ),
    ]
