# Generated by Django 4.2.27 on 2025-12-09 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_lesson_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='time_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='api.timeslot'),
        ),
    ]
