# Generated by Django 4.2.27 on 2025-12-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_lesson_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Якщо відмічено, цей семестр буде використовуватися за замовчуванням.', verbose_name='Поточний семестр'),
        ),
    ]
