# Generated by Django 4.2.27 on 2025-12-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_lesson_is_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_current',
        ),
        migrations.AddField(
            model_name='semester',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Якщо відмічено, цей семестр буде використовуватися за замовчуванням.', verbose_name='Поточний семестр'),
        ),
    ]
