# Generated by Django 4.2.27 on 2025-12-10 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_lesson_is_current_semester_is_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='slug',
        ),
    ]
