# Generated by Django 4.2.27 on 2025-12-10 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_roomtype_slug'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studyplan',
            name='study_plan_group_xor_stream',
        ),
        migrations.AlterUniqueTogether(
            name='studyplan',
            unique_together={('semester', 'subject', 'class_type', 'teacher', 'group'), ('semester', 'subject', 'class_type', 'teacher', 'stream')},
        ),
    ]
